# Generated by Django 3.0.7 on 2020-07-19 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='seller_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.')]),
        ),
    ]
