# Generated by Django 3.0.7 on 2020-07-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200719_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
