# Generated by Django 3.0.7 on 2020-07-19 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SiteUser',
        ),
    ]
