# Generated by Django 3.0.7 on 2020-07-23 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200719_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteUser',
            new_name='Vendor',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='user_id',
            new_name='vendor_id',
        ),
    ]
