# Generated by Django 3.0.7 on 2020-07-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200723_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='store_name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
