# Generated by Django 3.0.7 on 2020-08-04 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_sellerreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerReview',
            new_name='VendorReview',
        ),
        migrations.RenameField(
            model_name='vendorreview',
            old_name='seller',
            new_name='vendor',
        ),
    ]
