# Generated by Django 3.1.1 on 2020-11-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_vendor_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='about_image',
            field=models.ImageField(default='default.jpg', upload_to='store_pics'),
        ),
    ]
