# Generated by Django 3.0.7 on 2020-08-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_buyerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('b_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.BuyerProduct')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Category')),
            ],
            options={
                'unique_together': {('category', 'b_product')},
            },
        ),
    ]
