# Generated by Django 3.0.7 on 2020-08-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200818_1452'),
        ('admins', '0010_auto_20200804_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.SiteOrder'),
            preserve_default=False,
        ),
    ]
