# Generated by Django 3.0.7 on 2020-09-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_vendorreview_order'),
        ('admins', '0011_productreview_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Vendor')),
            ],
        ),
    ]
