# Generated by Django 3.0.7 on 2020-09-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_vendorreview_order'),
        ('admins', '0012_shippingrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingrate',
            name='vendor',
        ),
        migrations.CreateModel(
            name='VendorShipping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.ShippingRate')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Vendor')),
            ],
            options={
                'unique_together': {('rate', 'vendor')},
            },
        ),
    ]
