# Generated by Django 3.1.1 on 2020-10-04 16:09

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201004_1609'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('admins', '0014_auto_20201004_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceprovider'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.category'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceprovider'),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceitemcategory',
            unique_together={('category', 'service_item')},
        ),
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('category', 'service')},
        ),
    ]
