# Generated by Django 3.1.1 on 2020-10-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_auto_20201004_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompeeCares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
