# Generated by Django 3.1.1 on 2020-10-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_compeecares'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompeeCares',
            new_name='CompeeCaresRate',
        ),
    ]
