# Generated by Django 3.1.1 on 2020-10-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_productguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productguide',
            name='tags',
        ),
    ]
