# Generated by Django 3.1.1 on 2020-10-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_displaygroup_productgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaygroup',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='displaygroup',
            name='slug',
            field=models.SlugField(default='null', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
