# Generated by Django 3.1.1 on 2020-10-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_auto_20201009_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaygroup',
            name='enabled',
            field=models.BooleanField(choices=[('0', 'False'), ('1', 'True')], default=False),
        ),
    ]
