# Generated by Django 3.1.1 on 2020-10-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0026_auto_20201009_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='cat_pics'),
        ),
    ]
