# Generated by Django 3.1.1 on 2020-10-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0029_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='banner_pics'),
        ),
    ]
