# Generated by Django 3.0.7 on 2020-08-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteorder',
            name='status',
            field=models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=9),
        ),
    ]
