# Generated by Django 3.0.7 on 2020-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200810_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteorder',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('Unfulfilled', 'Unfulfilled'), ('Cancelled', 'Cancelled')], default='Unfulfilled', max_length=11),
        ),
    ]
