# Generated by Django 3.0.7 on 2020-08-15 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200815_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteorder',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.')]),
        ),
    ]
