# Generated by Django 3.0.7 on 2020-09-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_auto_20200902_0445'),
        ('main', '0010_auto_20200831_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteorder',
            name='shipping_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.ShippingRate'),
        ),
    ]
