# Generated by Django 3.0.7 on 2020-09-19 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_siteorder_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteorder',
            name='ref_id',
            field=models.CharField(blank=True, default='2009191730015E677F', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='siteorder',
            name='address_line',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('method', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Refund', 'Refund'), ('Incomplete', 'Incomplete'), ('Pending', 'Pending')], max_length=50, null=True)),
                ('pi', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('pm', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.SiteOrder')),
            ],
        ),
    ]
