# Generated by Django 3.0.7 on 2020-09-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200919_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteorder',
            name='ref_id',
            field=models.CharField(blank=True, default='2009271054426718DD', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='siteorder',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Shipped', 'Shipped'), ('Payment Pending', 'Payment Pending'), ('Unfulfilled', 'Unfulfilled'), ('Cancelled', 'Cancelled')], default='Unfulfilled', max_length=15),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
