# Generated by Django 3.1.1 on 2020-09-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200919_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteorder',
            name='ref_id',
            field=models.CharField(blank=True, default='200925151858833903', max_length=100, unique=True),
        ),
    ]
