# Generated by Django 3.1.1 on 2020-10-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200925_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteorder',
            name='ref_id',
            field=models.CharField(blank=True, default='201005145359F474E4', max_length=100, unique=True),
        ),
    ]
