# Generated by Django 3.1.1 on 2020-09-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200927_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteorder',
            name='ref_id',
            field=models.CharField(blank=True, default='2009271216110909DD', max_length=100, unique=True),
        ),
    ]
