# Generated by Django 3.1.1 on 2020-10-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201004_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='c_cares',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='c_cares',
            field=models.BooleanField(default=False),
        ),
    ]
