# Generated by Django 3.1.1 on 2020-10-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
