# Generated by Django 3.1.1 on 2020-10-22 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedWishlist',
            fields=[
                ('ref_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
